spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    br.com.chatiabe: DEBUG
    org.springframework.security: DEBUG
